version: '3'

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    container_name: backend
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "sleep 1
      && alembic revision --autogenerate -m "initial" &&
      alembic upgrade head &&
      python3 main.py"
